# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6736d1b01696c8b525d8b9316fe9ea9560288149567cbc3036d364ba160f5734bf4b04f7712c0238f89554b70a52a9e5ba2edac561da310ab87598543acad380

test:
  secret_key_base: 47552b72fc65655ef2982d740e9c22820b63d3553c010eb25c224a7f74de921b919debe19c499d0bf461130baa424f6ffb854156b8f62ddad0365d48213519fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
